/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safetybox;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author sam-y
 */
public class Administrador_archivos extends javax.swing.JFrame {

    JFileChooser seleccionado = new JFileChooser();
    //File archivo;
    String ruta = "";
    byte[] bytesImg;
    //GestionA gestion;
    FileInputStream entrada;
    FileOutputStream salida;
    DES_AES DesAesCipher = new DES_AES();

    /**
     * Creates new form Administrador_archivos
     */
    public Administrador_archivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAbrirArchivo = new javax.swing.JButton();
        btnEncryptImage = new javax.swing.JButton();
        lblimagen = new javax.swing.JLabel();
        BtnDecryptImage = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Archivos");

        BtnAbrirArchivo.setText("Abrir archivo");
        BtnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirArchivoActionPerformed(evt);
            }
        });

        btnEncryptImage.setText("Encrypt");
        btnEncryptImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptImageActionPerformed(evt);
            }
        });

        lblimagen.setText("Seleccionaste el archivo: *******");

        BtnDecryptImage.setText("Decrypt");
        BtnDecryptImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDecryptImageActionPerformed(evt);
            }
        });

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnEncryptImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnDecryptImage)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(BtnAbrirArchivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblimagen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAbrirArchivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncryptImage)
                    .addComponent(BtnDecryptImage))
                .addGap(18, 18, 18)
                .addComponent(lblimagen)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirArchivoActionPerformed
        if (seleccionado.showDialog(null, "Abrir archivo") == JFileChooser.APPROVE_OPTION) {
            File archivo = seleccionado.getSelectedFile();
            ruta = archivo.getAbsolutePath();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("bmp")) {
                    bytesImg = AbrirAImagen(archivo);
                    System.out.println(bytesImg);
                    //this.lblimagen.setIcon(new ImageIcon(bytesImg));
                    this.lblimagen.setText("Seleccionaste el archivo: " + archivo.getName());
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo .bmp");
                }

            }
        }
    }//GEN-LAST:event_BtnAbrirArchivoActionPerformed

 
    public String AbrirTexto(File archivo) {
        String contenido = "";
        try {
            FileInputStream entrada = new FileInputStream(archivo);
            int ascci;
            while ((ascci = entrada.read()) != -1) {
                char caracter = (char) ascci;
                contenido += caracter;
            }
        } catch (IOException ex) {
        }
        return contenido;
    }

    public String GuardarATexto(File archivo, String contenido) throws IOException {
        String respuesta = null;
        try {
            salida = new FileOutputStream(archivo);
            byte[] bytesTxt = contenido.getBytes();
            salida.write(bytesTxt);
            respuesta = "Se guardo el archivo";
        } catch (FileNotFoundException ex) {
        }
        return respuesta;
    }

    public byte[] AbrirAImagen(File archivo) {
        byte[] bytesImg = new byte[1024 * 1024 * 100];
        try {
            entrada = new FileInputStream(archivo);
            entrada.read(bytesImg);
            entrada.close();
        } catch (Exception e) {
        }
        return bytesImg;
    }

    public String decifrarImagen(File archivo) {
        String respuesta = null;
        try {
            DesAesCipher.initDES_AES();//inicio DES_AES
            FileInputStream Fin_d = new FileInputStream(archivo.getAbsolutePath());
            FileOutputStream Fout_d = new FileOutputStream(archivo.getParent() + "/gftsal" + archivo.getName());
            System.out.println(archivo.getParent());
            DesAesCipher.Decrypt(Fin_d, Fout_d);
            respuesta = "La imagen se guardo";
        } catch (Exception ex) {
            System.out.println(archivo.getParent());
            Logger.getLogger(Administrador_archivos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return respuesta;
    }
    
    public String cifrarImagen(File archivo) {
        String respuesta = null;
        try {
            DesAesCipher.initDES_AES();//inicio DES_AES
            FileInputStream Fin_d = new FileInputStream(archivo.getAbsolutePath());
            FileOutputStream Fout_d = new FileOutputStream(archivo.getParent() + "/gftsal" + archivo.getName());
            System.out.println(archivo.getParent());
            DesAesCipher.Encrypt(Fin_d, Fout_d);
            respuesta = "La imagen se guardo";
        } catch (Exception ex) {
            System.out.println(archivo.getParent());
            Logger.getLogger(Administrador_archivos.class.getName()).log(Level.SEVERE, null, ex);
        }
        return respuesta;
    }
    private void btnEncryptImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptImageActionPerformed
        File archivo = new File(ruta);
        if (archivo.getName().endsWith(".bmp")) {
            String respuesta = cifrarImagen(archivo);
            if (respuesta != null) {
                File a = new File(archivo.getAbsolutePath());
                a.delete();
                File b = new File(archivo.getParent() + "/gftsal" + archivo.getName());
                b.renameTo(a);                
                JOptionPane.showMessageDialog(null, respuesta);
            } else {
                JOptionPane.showMessageDialog(null, "error al guardar imagen");
            }
        } else {
            JOptionPane.showMessageDialog(null, "la imagen se debe guardar en formato .bmp");
        }
    }//GEN-LAST:event_btnEncryptImageActionPerformed

    private void BtnDecryptImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDecryptImageActionPerformed
        File archivo = new File(ruta);
        if (archivo.getName().endsWith(".bmp")) {
            String respuesta = decifrarImagen(archivo);
            if (respuesta != null) {
                File a = new File(archivo.getAbsolutePath());
                a.delete();
                File b = new File(archivo.getParent() + "/gftsal" + archivo.getName());
                b.renameTo(a);
                JOptionPane.showMessageDialog(null, respuesta);
            } else {
                JOptionPane.showMessageDialog(null, "error al guardar imagen");
            }
        } else {
            JOptionPane.showMessageDialog(null, "la imagen se debe guardar en formato .bmp");
        }
    }//GEN-LAST:event_BtnDecryptImageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new calculadora().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador_archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador_archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador_archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador_archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador_archivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbrirArchivo;
    private javax.swing.JButton BtnDecryptImage;
    private javax.swing.JButton btnEncryptImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblimagen;
    // End of variables declaration//GEN-END:variables
}
